### ISSUE TITLE
List View

### ISSUE THREAD

**Issue by brannondorsey** [brannondorsey/ProbeRequestCollectorsKit#10]
It would be helpful to implement a list view to better understand the data being collected as a whole. These views would be a simple list of all networks and devices collected and accessible by clicking Devices or Networks from the stats display (or via another interface).

**Comment by nbriz** [comment]
maybe we can make this a modal for network lists && also add manufacturers to bottom left + linst in a modal of its own when clicked

**Comment by brannondorsey** [comment]
This would be a nice feature to have for the workshop. Moving this to milestone v0.3.0.

**Comment by brannondorsey** [comment]
Network stats now displays all networks in alphabetical order in the modal when clicked. These can all be applied as filters.
