### ISSUE TITLE
db 4 real

### ISSUE THREAD

**Issue by nbriz** [brannondorsey/ProbeRequestCollectorsKit#11]
csv is crafty, but at some point it might be time for a real database >> i'm told this is a good mongodb ntro: [the little mongodb book](http://openmymind.net/mongodb.pdf)

**Comment by brannondorsey** [comment]
With the optimizations we have recently made (in preparation for a v0.3.0 release) the need for a MongoDB database to log, manage, and serve caught probes is no longer that high. We currently have an in-memory representation of this data on the server side with `src/ProbeDataStore.js`, and also an in-memory representation of this in the browser (or NodeWebkit instance) that is parsed from the `probes.csv` file every page load.
