### ISSUE TITLE
toggle wifi / monitor mode

### ISSUE THREAD

**Issue by nbriz** [brannondorsey/ProbeRequestCollectorsKit#22]
for when folks go between butterfly capture mode && map view

**Comment by brannondorsey** [comment]
If no internet connection is detected in Maps view notify user that they need to connect to the internet to view maps.

**Comment by brannondorsey** [comment]
If we get [offline maps](https://github.com/brannondorsey/ProbeRequestCollectorsKit/issues/27) working this won't be needed. Closing for now.
